### ISSUE TITLE
operation error Lambda: ListFunctions, could not select an auth scheme

### ISSUE THREAD

**Issue by shogo82148** [shogo82148/aws-xray-yasdk-go#510]
Test fail with newer version of AWS SDK v2.
since https://github.com/shogo82148/aws-xray-yasdk-go/pull/504

**Comment by shogo82148** [comment]
The log: https://github.com/shogo82148/aws-xray-yasdk-go/actions/runs/6891559160/job/18746874218

```
=== RUN   TestClient
    client_test.go:121: operation error Lambda: ListFunctions, could not select an auth scheme
--- FAIL: TestClient (0.00s)
=== RUN   TestClient_FailDial
    client_test.go:246: operation error Lambda: ListFunctions, could not select an auth scheme
--- FAIL: TestClient_FailDial (0.00s)
=== RUN   TestClient_BadRequest
    client_test.go:397: expected *smithyhttp.ResponseError, but not
--- FAIL: TestClient_BadRequest (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb0e585]

goroutine 24 [running]:
testing.tRunner.func1.2({0xb89000, 0x10579b0})
	/opt/hostedtoolcache/go/1.21.4/x64/src/testing/testing.go:1545 +0x366
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.4/x64/src/testing/testing.go:1548 +0x630
panic({0xb89000?, 0x10579b0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:920 +0x270
github.com/aws/aws-sdk-go-v2/aws/transport/http.(*ResponseError).Error(...)
	/home/runner/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.23.0/aws/transport/http/response_error.go:26
github.com/shogo82148/aws-xray-yasdk-go/xrayaws-v2.TestClient_BadRequest(0xc000274b60)
	/home/runner/work/aws-xray-yasdk-go/aws-xray-yasdk-go/xrayaws-v2/client_test.go:487 +0xa45
testing.tRunner(0xc000274b60, 0xc51e50)
	/opt/hostedtoolcache/go/1.21.4/x64/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.4/x64/src/testing/testing.go:1648 +0x82b
FAIL	github.com/shogo82148/aws-xray-yasdk-go/xrayaws-v2	0.022s
FAIL
make: *** [Makefile:18: test-xrayaws-v2] Error 1
```
